from dotenv import load_dotenv
# Load API credentials and other settings from the local environment file.
load_dotenv()

# Import the document, embedding, model, vector-store, and graph components used below.
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters  import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_community.vectorstores import InMemoryVectorStore

from langgraph.graph import StateGraph, START, END
from pydantic import BaseModel, Field


# RAG processing steps:
# 1. Load the source PDF and split it into overlapping chunks.
# 2. Embed and index the chunks for semantic search.
# 3. Retrieve relevant chunks for the user's question.
# 4. Combine the retrieved text into context.
# 5. Generate an answer grounded in that context.


# Preparation step 1: Load the source PDF and split it into overlapping chunks.
loader = PyPDFLoader("../data/Artificial Intelligence Overview.pdf")
docs  = loader.load()

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
split_docs = splitter.split_documents(docs)

# Preparation step 2: Embed the chunks and index them for semantic retrieval.
embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-2-preview",)

vector_store = InMemoryVectorStore.from_documents(
    documents=split_docs, 
    embedding=embeddings,
    collection_name="rag_langraph_19_notebook"
    )

# Configure the language model that will produce the final answer.
llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash-lite")


# Define the data carried between the retrieval, context, and answer graph nodes.
class RagState(BaseModel):
    question: str = Field(description="The question to be asked in the RAG system")
    document:list = []
    context: str = Field(default="", description="The context retrieved from the documents")
    answer: str = Field(default="", description="The answer generated by the RAG system")



# Query step 1: Retrieve the document chunks most relevant to the question.
def retrieve_docs_node(state: RagState) -> RagState:
    print("[retrieve_node]: Starting document retrieval")
    retrieved_docs = vector_store.similarity_search(state.question)
    state.document = retrieved_docs
    return state


# Query step 2: Combine retrieved chunk text into context for the answer model.
def context_extraction_node(state: RagState) -> RagState:
    print("[context_extraction_node]: Extracting context from retrieved documents...")
    context = ""
    for doc in state.document:
        context += doc.page_content + "\n"
    state.context = context
    return state


# Query step 3: Generate an answer from the context without unsupported claims.
def generate_answer_node(state: RagState) -> RagState:
    print("[generate_answer_node]: Generating answer based on context")
    prompt = f"""
        You are an assistant and provide the answer for the question based on the given context.
        dont make up an answer if the context does not contain the information. just say you don't know.
        question: {state.question},
        context: {state.context} 
    """
    response = llm.invoke(prompt)
    state.answer = response.content
    return state


# Connect the three query steps in order: retrieval, context extraction, and generation.
graph = StateGraph(RagState)

graph.add_node("retrieve_docs", retrieve_docs_node)
graph.add_node("extract_context", context_extraction_node)
graph.add_node("generate_answer", generate_answer_node)

graph.add_edge(START, "retrieve_docs")
graph.add_edge("retrieve_docs", "extract_context")
graph.add_edge("extract_context", "generate_answer")
graph.add_edge("generate_answer", END)

# Compile the graph and run it with the question to be answered.
graph = graph.compile()
# Process the question through retrieval, context extraction, and answer generation.
res = graph.invoke({"question": "what this document is about"})

# Print the text content from the model's response.
print(res["answer"][0]["text"])










